return {
    { name = "successful gathering links the observed start without claiming a resource or yield", run = function(Host)
        local h = Host.new()
        h:start()
        h:event("UNIT_SPELLCAST_START", "player", "Cast-1", 2575)
        h:event("UNIT_SPELLCAST_SUCCEEDED", "player", "Cast-1", 2575)
        local start   = h:records("gathering.attempt")[1]
        local success = h:records("spell.succeeded")[1]
        assert(start.data.profession == "mining" and start.data.outcome == "started")
        assert(start.data.attempt_id == success.data.gathering_attempt_id)
        assert(success.related_observation_ids[1] == start.observation_id)
        assert(start.data.resource_identity == "not_observed" and start.data.received_items == "not_attributed")
        h:assertHealthy()
    end },
    { name = "failure and interruption retain distinct identities and never link unrelated casts", run = function(Host)
        local h = Host.new()
        h:start()
        h:event("UNIT_SPELLCAST_START", "player", "Cast-1", 2366)
        h:event("UNIT_SPELLCAST_FAILED", "player", "Cast-other", 2366)
        local uncorrelated = h:records("gathering.attempt")[2]
        assert(uncorrelated.data.start_match_status == "unavailable" and #uncorrelated.related_observation_ids == 0)
        h:event("UNIT_SPELLCAST_FAILED", "player", "Cast-1", 2366)
        h:event("UNIT_SPELLCAST_START", "player", "Cast-2", 8613)
        h:event("UNIT_SPELLCAST_INTERRUPTED", "player", "Cast-2", 8613)
        local records = h:records("gathering.attempt")
        assert(#records == 5 and records[3].data.outcome == "failed" and records[5].data.outcome == "interrupted")
        assert(records[1].data.attempt_id ~= records[4].data.attempt_id)
        h:assertHealthy()
    end },
    { name = "fishing channel events do not duplicate start or reopen a successful cast", run = function(Host)
        local h = Host.new()
        h:start()
        h:event("UNIT_SPELLCAST_START", "player", "Cast-1", 7620)
        h:event("UNIT_SPELLCAST_CHANNEL_START", "player", "Cast-1", 7620)
        assert(#h:records("gathering.attempt") == 1)
        h:event("UNIT_SPELLCAST_SUCCEEDED", "player", "Cast-1", 7620)
        h:event("UNIT_SPELLCAST_CHANNEL_START", "player", "Cast-1", 7620)
        h:event("UNIT_SPELLCAST_INTERRUPTED", "player", "Cast-1", 7620)
        assert(#h:records("gathering.attempt") == 1)
        assert(h:records("gathering.attempt")[1].data.profession == "fishing")
        h:assertHealthy()
    end },
    { name = "pause clears unfinished attempt links and instant success has an identity", run = function(Host)
        local h = Host.new()
        h:start()
        h:event("UNIT_SPELLCAST_START", "player", "Cast-1", 2575)
        h.FT.Pause(true)
        h.FT.Pause(false)
        h:event("UNIT_SPELLCAST_FAILED", "player", "Cast-1", 2575)
        assert(h:records("gathering.attempt")[2].data.start_match_status == "unavailable")
        h:event("UNIT_SPELLCAST_SUCCEEDED", "player", "Cast-2", 2575)
        local success = h:records("spell.succeeded")[1]
        assert(type(success.data.gathering_attempt_id) == "string" and #success.related_observation_ids == 0)
        h:assertHealthy()
    end },
    { name = "unknown spells and non-player casts do not become gathering attempts", run = function(Host)
        local h = Host.new()
        h:start()
        h:event("UNIT_SPELLCAST_START", "player", "Cast-1", 1240952)
        h:event("UNIT_SPELLCAST_START", "pet", "Cast-2", 2575)
        h:event("UNIT_SPELLCAST_CHANNEL_START", "player", "Cast-3", 13615)
        assert(#h:records("gathering.attempt") == 0)
        h:event("UNIT_SPELLCAST_SUCCEEDED", "player", "Cast-4", 75)
        assert(h:records("spell.succeeded")[1].data.gathering_attempt_id == nil)
        h:assertHealthy()
    end },
    { name = "unreadable cast identities never deduplicate or correlate attempts", run = function(Host)
        local h = Host.new()
        h:start()
        h:event("UNIT_SPELLCAST_START", "player", nil, 2575)
        h:event("UNIT_SPELLCAST_START", "player", nil, 2575)
        h:event("UNIT_SPELLCAST_FAILED", "player", nil, 2575)
        local records = h:records("gathering.attempt")
        assert(#records == 3 and records[1].data.attempt_id ~= records[2].data.attempt_id)
        assert(records[3].data.start_match_status == "unavailable" and #records[3].related_observation_ids == 0)
        h:assertHealthy()
    end },
}
